### Update Patient
PUT http://localhost:4000/patients/223e4567-e89b-12d3-a456-426614174014
Content-Type: application/json

{
  "name": "John Doe UPDATED",
  "email": "test123@example.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09"
}
